# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EscolherMusica.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(20, 480, 121, 61))
        self.btn_play.setStyleSheet("background-color: green;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"border-radius: 10px;")
        self.btn_play.setObjectName("btn_play")
        self.btn_parar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_parar.setGeometry(QtCore.QRect(660, 480, 121, 61))
        self.btn_parar.setStyleSheet("background-color: red;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"border-radius: 10px;")
        self.btn_parar.setObjectName("btn_parar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 249, 33))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 50, 298, 16))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 70, 298, 16))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 90, 298, 16))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 110, 298, 16))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 130, 298, 16))
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(250, 180, 301, 20))
        self.input.setObjectName("input")
        self.btn_pause = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pause.setGeometry(QtCore.QRect(350, 480, 121, 61))
        self.btn_pause.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 226, 58);\n"
"color: black;\n"
"border-radius: 10px;")
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 200, 801, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.msg_erro = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.msg_erro.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: red;")
        self.msg_erro.setText("")
        self.msg_erro.setObjectName("msg_erro")
        self.horizontalLayout.addWidget(self.msg_erro)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.volume = QtWidgets.QSlider(self.centralwidget)
        self.volume.setGeometry(QtCore.QRect(320, 340, 160, 22))
        self.volume.setMinimum(0)
        self.volume.setOrientation(QtCore.Qt.Horizontal)
        self.volume.setObjectName("volume")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(375, 320, 51, 16))
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_play.setText(_translate("MainWindow", "Play"))
        self.btn_parar.setText(_translate("MainWindow", "Parar"))
        self.label.setText(_translate("MainWindow", "Escolha uma música:"))
        self.label_2.setText(_translate("MainWindow", "1 - Pelados em Santos | Mamonas Assasinas | 3:00"))
        self.label_3.setText(_translate("MainWindow", "2 - Roda Roda Vira | Mamonas Assasinas | 2:33"))
        self.label_4.setText(_translate("MainWindow", "3 - Jennifer | Gabriel Dinis | 1:59"))
        self.label_5.setText(_translate("MainWindow", "4 - Descer pra BC | Breno e Mateus | 2:44"))
        self.label_6.setText(_translate("MainWindow", "5 - Descer pra CG | Nícolas Concordo | 25:00"))
        self.btn_pause.setText(_translate("MainWindow", "Pause"))
        self.label_7.setText(_translate("MainWindow", "Volume:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
