# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExJSON.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.feminino = QtWidgets.QRadioButton(self.centralwidget)
        self.feminino.setGeometry(QtCore.QRect(310, 230, 77, 17))
        self.feminino.setObjectName("feminino")
        self.btnSair = QtWidgets.QPushButton(self.centralwidget)
        self.btnSair.setGeometry(QtCore.QRect(370, 350, 91, 41))
        self.btnSair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSair.setObjectName("btnSair")
        self.btnCarregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCarregar.setGeometry(QtCore.QRect(270, 350, 101, 41))
        self.btnCarregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCarregar.setObjectName("btnCarregar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 60, 31, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 100, 100, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 140, 41, 20))
        self.label_3.setStyleSheet("text-align: center;")
        self.label_3.setObjectName("label_3")
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalvar.setGeometry(QtCore.QRect(370, 310, 91, 41))
        self.btnSalvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSalvar.setObjectName("btnSalvar")
        self.masculino = QtWidgets.QRadioButton(self.centralwidget)
        self.masculino.setGeometry(QtCore.QRect(310, 210, 75, 17))
        self.masculino.setObjectName("masculino")
        self.dtNasc = QtWidgets.QDateEdit(self.centralwidget)
        self.dtNasc.setGeometry(QtCore.QRect(310, 90, 81, 41))
        self.dtNasc.setObjectName("dtNasc")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 180, 41, 20))
        self.label_4.setObjectName("label_4")
        self.altura = QtWidgets.QLineEdit(self.centralwidget)
        self.altura.setGeometry(QtCore.QRect(310, 180, 146, 20))
        self.altura.setObjectName("altura")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 220, 41, 17))
        self.label_5.setObjectName("label_5")
        self.nome = QtWidgets.QLineEdit(self.centralwidget)
        self.nome.setGeometry(QtCore.QRect(306, 59, 239, 20))
        self.nome.setObjectName("nome")
        self.idade = QtWidgets.QLineEdit(self.centralwidget)
        self.idade.setGeometry(QtCore.QRect(310, 140, 158, 20))
        self.idade.setObjectName("idade")
        self.btnNovoJogo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNovoJogo.setGeometry(QtCore.QRect(270, 310, 100, 41))
        self.btnNovoJogo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNovoJogo.setObjectName("btnNovoJogo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.feminino.setText(_translate("MainWindow", "Feminino"))
        self.btnSair.setText(_translate("MainWindow", "Sair"))
        self.btnCarregar.setText(_translate("MainWindow", "Carregar Jogo"))
        self.label.setText(_translate("MainWindow", "Nome:"))
        self.label_2.setText(_translate("MainWindow", "Data de Nascimento:"))
        self.label_3.setText(_translate("MainWindow", "Idade:"))
        self.btnSalvar.setText(_translate("MainWindow", "Salvar Jogo"))
        self.masculino.setText(_translate("MainWindow", "Masculino"))
        self.label_4.setText(_translate("MainWindow", "Altura:"))
        self.label_5.setText(_translate("MainWindow", "Sexo:"))
        self.btnNovoJogo.setText(_translate("MainWindow", "Novo Jogo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
