# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExConcurso.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 425, 35))
        self.label.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 130, 33, 19))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.cpf.setGeometry(QtCore.QRect(345, 130, 151, 20))
        self.cpf.setObjectName("cpf")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 240, 316, 23))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.notaPortugues = QtWidgets.QLineEdit(self.centralwidget)
        self.notaPortugues.setGeometry(QtCore.QRect(190, 280, 151, 20))
        self.notaPortugues.setObjectName("notaPortugues")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 280, 77, 19))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.notaMatematica = QtWidgets.QLineEdit(self.centralwidget)
        self.notaMatematica.setGeometry(QtCore.QRect(190, 320, 151, 20))
        self.notaMatematica.setObjectName("notaMatematica")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 320, 85, 19))
        self.label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.notaConGerais = QtWidgets.QLineEdit(self.centralwidget)
        self.notaConGerais.setGeometry(QtCore.QRect(270, 360, 151, 20))
        self.notaConGerais.setObjectName("notaConGerais")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 360, 163, 19))
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.notaConEspec = QtWidgets.QLineEdit(self.centralwidget)
        self.notaConEspec.setGeometry(QtCore.QRect(300, 400, 151, 20))
        self.notaConEspec.setObjectName("notaConEspec")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 400, 195, 19))
        self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.btnCalcular = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcular.setGeometry(QtCore.QRect(280, 490, 101, 41))
        self.btnCalcular.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.btnCalcular.setObjectName("btnCalcular")
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalvar.setGeometry(QtCore.QRect(440, 490, 101, 41))
        self.btnSalvar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.btnSalvar.setObjectName("btnSalvar")
        self.btnLimparCampos = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimparCampos.setGeometry(QtCore.QRect(710, 520, 81, 31))
        self.btnLimparCampos.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 25, 25);\n"
"color: white;")
        self.btnLimparCampos.setObjectName("btnLimparCampos")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cadastro das Notas do Candidato"))
        self.label_2.setText(_translate("MainWindow", "CPF:"))
        self.label_3.setText(_translate("MainWindow", "Informe a quantidade de acertos em:"))
        self.label_4.setText(_translate("MainWindow", "Português:"))
        self.label_5.setText(_translate("MainWindow", "Matemática:"))
        self.label_6.setText(_translate("MainWindow", "Conhecimentos Gerais:"))
        self.label_7.setText(_translate("MainWindow", "Conhecimentos Específicos:"))
        self.btnCalcular.setText(_translate("MainWindow", "Calcular"))
        self.btnSalvar.setText(_translate("MainWindow", "Salvar Notas"))
        self.btnLimparCampos.setText(_translate("MainWindow", "Limpar Campos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
