# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaInicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 282)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_fundo_2 = QtWidgets.QWidget(self.centralwidget)
        self.img_fundo_2.setGeometry(QtCore.QRect(0, -10, 530, 280))
        self.img_fundo_2.setStyleSheet("image: url(\"C://Users//NícolasEloy//Documents//Dev-desktop//Projeto_21//imagens//tela-verde.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.img_fundo_2.setObjectName("img_fundo_2")
        self.frame = QtWidgets.QFrame(self.img_fundo_2)
        self.frame.setGeometry(QtCore.QRect(40, 190, 71, 91))
        self.frame.setStyleSheet("image: url(\"C://Users//NícolasEloy//Documents//Dev-desktop//Projeto_21//imagens//cartas-viradas\");")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.img_fundo_2)
        self.frame_2.setGeometry(QtCore.QRect(110, 50, 321, 171))
        self.frame_2.setStyleSheet("image: url(\"C://Users//NícolasEloy//Documents//Dev-desktop//Projeto_21//imagens//mesa-principal\");")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.img_fundo_2)
        self.frame_3.setGeometry(QtCore.QRect(263, 178, 181, 111))
        self.frame_3.setStyleSheet("image: url(\"C://Users//NícolasEloy//Documents//Dev-desktop//Projeto_21//imagens//btn-parar-des\");")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.img_fundo_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 93, 11))
        self.label.setStyleSheet("color: white;\n"
"font: 7pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.botao_parar = QtWidgets.QPushButton(self.img_fundo_2)
        self.botao_parar.setGeometry(QtCore.QRect(310, 230, 91, 31))
        self.botao_parar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_parar.setStyleSheet("color: transparent;\n"
"background-color: transparent;\n"
"image: none;")
        self.botao_parar.setObjectName("botao_parar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.img_fundo_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 531, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.soma = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.soma.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: yellow;\n"
"font-weight: 600;")
        self.soma.setText("")
        self.soma.setObjectName("soma")
        self.horizontalLayout_2.addWidget(self.soma)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.frame_5 = QtWidgets.QFrame(self.img_fundo_2)
        self.frame_5.setGeometry(QtCore.QRect(380, 194, 151, 81))
        self.frame_5.setMaximumSize(QtCore.QSize(200, 200))
        self.frame_5.setStyleSheet("image: url(\"C://Users//NícolasEloy//Documents//Dev-desktop//Projeto_21//imagens//btn-continuar.png\");")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_3.raise_()
        self.frame.raise_()
        self.label.raise_()
        self.horizontalLayoutWidget.raise_()
        self.frame_5.raise_()
        self.frame_2.raise_()
        self.botao_parar.raise_()
        self.botao_continuar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_continuar.setGeometry(QtCore.QRect(430, 220, 81, 31))
        self.botao_continuar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_continuar.setStyleSheet("color: transparent;\n"
"background-color: transparent;")
        self.botao_continuar.setObjectName("botao_continuar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Clique em “Continuar”"))
        self.botao_parar.setText(_translate("MainWindow", "PushButton"))
        self.botao_continuar.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
