# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_fundo = QtWidgets.QFrame(self.centralwidget)
        self.img_fundo.setGeometry(QtCore.QRect(-50, -21, 2021, 1121))
        self.img_fundo.setStyleSheet("image: url(\"C://Users//NícolasEloy//Documents//Dev-desktop//Projeto_21//imagens//img-fundo.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.img_fundo.setObjectName("img_fundo")
        self.widget = QtWidgets.QWidget(self.img_fundo)
        self.widget.setGeometry(QtCore.QRect(160, -50, 1661, 911))
        self.widget.setStyleSheet("image: url(\"C://Users//NícolasEloy//Documents//Dev-desktop//Projeto_21//imagens//cartas.png\");\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.img_fundo)
        self.label.setGeometry(QtCore.QRect(630, 510, 774, 314))
        self.label.setStyleSheet("image: none;\n"
"font: 200pt \"Freestyle Script\";\n"
"color: white;")
        self.label.setObjectName("label")
        self.btnStart = QtWidgets.QPushButton(self.img_fundo)
        self.btnStart.setGeometry(QtCore.QRect(900, 770, 161, 51))
        self.btnStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStart.setStyleSheet("image: none;\n"
"border-radius: 10px;\n"
"background-color: #D9D9D9;\n"
"font: 30pt;")
        self.btnStart.setObjectName("btnStart")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BlackJack"))
        self.btnStart.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
